
-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Oct 13, 2016 at 09:59 AM
-- Server version: 10.0.20-MariaDB
-- PHP Version: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `u413924127_cars`
--

-- --------------------------------------------------------

--
-- Table structure for table `car`
--

CREATE TABLE IF NOT EXISTS `car` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `price` decimal(9,2) unsigned DEFAULT NULL,
  `car_type` enum('Hatchback','Sedan','MUV','SUV','Hybrid','Coupe','Çonvertible') DEFAULT NULL,
  `make` varchar(255) DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `mileagec` int(10) DEFAULT NULL,
  `mileageh` int(10) DEFAULT NULL,
  `power` int(10) DEFAULT NULL,
  `torque` int(10) DEFAULT NULL,
  `top_speed` int(10) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `doors` int(10) DEFAULT NULL,
  `fuel` enum('Petrol','Diesal','Both') DEFAULT NULL,
  `transmisson` enum('Manual','Automatic','Both') DEFAULT NULL,
  `number_of_seats` int(10) DEFAULT NULL,
  `fuelcapacity` int(10) DEFAULT NULL,
  `ddesc` varchar(10255) DEFAULT NULL,
  `cylinders` int(10) DEFAULT NULL,
  ` zerotosixty` int(10) DEFAULT NULL,
  `Length` int(10) DEFAULT NULL,
  `Width` int(10) DEFAULT NULL,
  `Height` int(10) DEFAULT NULL,
  `Wheelbase` int(10) DEFAULT NULL,
  `Kerbweight` int(10) DEFAULT NULL,
  `groundclearence` int(10) DEFAULT NULL,
  `bootcapacity` int(10) DEFAULT NULL,
  `video` varchar(255) DEFAULT NULL,
  `photo1` varchar(255) DEFAULT NULL,
  `photo2` varchar(255) DEFAULT NULL,
  `photo3` varchar(255) DEFAULT NULL,
  `photo4` varchar(255) DEFAULT NULL,
  `photo5` varchar(255) DEFAULT NULL,
  `photo6` varchar(255) DEFAULT NULL,
  `photo7` varchar(255) DEFAULT NULL,
  `photo8` varchar(255) DEFAULT NULL,
  `photo9` varchar(255) DEFAULT NULL,
  `photo10` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=111 ;

--
-- Dumping data for table `car`
--

INSERT INTO `car` (`id`, `title`, `price`, `car_type`, `make`, `model`, `mileagec`, `mileageh`, `power`, `torque`, `top_speed`, `color`, `doors`, `fuel`, `transmisson`, `number_of_seats`, `fuelcapacity`, `ddesc`, `cylinders`, ` zerotosixty`, `Length`, `Width`, `Height`, `Wheelbase`, `Kerbweight`, `groundclearence`, `bootcapacity`, `video`, `photo1`, `photo2`, `photo3`, `photo4`, `photo5`, `photo6`, `photo7`, `photo8`, `photo9`, `photo10`) VALUES
(26, 'Hyundai Grand i10', '6.42', 'Hatchback', 'Hyundai', 'Grand i10', 16, 20, 70, 160, 154, 'Silver , White , Black , Red , Blue', 5, 'Petrol', 'Manual', 5, 43, 'The Grand i10 fits right between the i10 and the i20. Both, in terms of price and dimensions. But wait; don’t mistake the Grand i10 to be the i10’s successor in the European markets. This Grand i10 is 10cm longer than the European one and this addition has been made considering the Indian conditions.  Like most other Hyundais today, the Grand i10 too carries forward Hyundai’s Fluidic design theme. And like other Hyundais, the Grand looks pretty to the eye. Swept-back headlamps and a big hexagonal grille with chunky fog lamps add zest to the front. Sharp lines and the body moulding make sure the zest is carried through the profile of the Grand i10. At the rear too, the styling is anything but bland. The large bumper wraps the whole thing pretty neatly.  On the inside, the Grand i10 looks nothing like the i10 or the i20. It’s an all-new design. Beige and black plastics are used nicely, and you get brushed-aluminium dials for the air-con vents that look tastefully made. The overall fit and finish and the plastic quality is pretty good, and is one of the best in the segment.', 3, 10, 3765, 1660, 1520, 2425, 1250, 180, 243, 'https://youtu.be/Zp_uFU8ml-0', 'I101.jpg', 'I102.jpg', 'I103.jpg', 'I104.jpg', 'I105.jpg', 'I106.jpg', 'I107.jpg', 'I108.jpg', 'I109.jpg', 'I1010.jpg'),
(1, 'Volkswagen Polo ', '9.30', 'Hatchback', 'Volkswagen', 'Polo', 16, 20, 89, 230, 163, 'Red, Black, Grey, Silver', 5, 'Both', 'Both', 5, 45, 'VW Polo has been spied with new headlamps featuring LED daytime running lights. It is expected that the German automaker will launch it sometime this year with a few other updates. Earlier from last month, Polo GTI was unveiled at the 2016 Indian Auto Expo, New Delhi. Reports claim, that the official launch of the hatchback has been slated for the month of September and will rival against Abarth Punto Evo. Under the bonnet, Polo GTi features VW’s 1.8-litre TSi turbocharged petrol engine that generates 192 PS of power output and 250 Nm of peak torque. The 1.8-litre unit comes mated to a 7-Speed DSG automatic transmission.', 4, 10, 3971, 1682, 1469, 2469, 1126, 165, 280, 'https://www.youtube.com/watch?v=ZyBRPHPNwMU', 'polo1.jpg', 'polo2.jpg', 'polo3.jpg', 'polo4.jpg', 'polo5.jpg', 'polo6.jpg', 'polo7.jpg', 'polo8.jpg', 'polo9.jpg', 'polo10.jpg'),
(27, 'Hyundai Verna ', '9.00', 'Sedan', 'Hyundai  ', 'Verna', 12, 18, 89, 220, 162, 'White , Blue , Black', 5, 'Both', 'Both', 5, 43, 'Hyundai introduced the mid-life update of the Verna last year in February and is now dubbed as Verna 4S. The sedan is available in the price band of Rs 7.60 - 13.08 lakh. Like before, it largely competes with the Honda City and the Maruti Suzuki Ciaz along with other midsize sedans. The 4S comes with a fresh new face, while the side and the rear profiles were largely unchanged; save for the new graphics for the taillamps and subtle changes to the rear bumper. The facelift has also added new feature including six airbags (re-added). While a few features were added this year as well, for example, the touchscreen infotainment system with rearview camera. Mechanically, the Verna 4S is available with four (two each of petrol and diesel) engine options. ', 4, 10, 4375, 1700, 1475, 2570, 1800, 165, 465, 'https://youtu.be/QHVgLb1lyAw', 'verna1.jpg', 'verna2.jpg', 'verna3.jpg', 'verna4.jpg', 'verna5.jpg', 'verna6.jpg', 'verna7.jpg', 'verna8.jpg', 'verna9.jpg', 'verna10.jpg'),
(2, 'Volkswagen Vento', '11.60', 'Sedan', 'Volkswagen', 'Vento', 16, 20, 104, 240, 180, 'Silver, Grey, Blue, Black', 4, 'Both', 'Both', 5, 55, 'The Volkswagen Vento with the 1.2-litre TSI engine has been given a five-star rating from the ASEAN NCAP. This car was tested earlier by the same organization and was given a four-star rating. This update in rating comes as the manufacturer has now added Electronic Stabilisation Programme (ESP) in the vehicle. Also, the Vento was recently updated and now comes with a touchscreen infotainment system with MirrorLink, which allows you to pair your Android device with the car’s infotainment system. Moreover, the updated car gets phone book/SMS viewer, auto dimming IRVM, and rain-sensing wipers. In India, the Vento is available with three engine options -- the 1.2 TSI, the 1.6-litre MPI petrol, and the 1.5-litre TDI diesel. As mentioned above, the updated rating is only given to the 1.2-litre TSI variant.', 4, 7, 4384, 1699, 1466, 2552, 1220, 167, 480, 'https://www.youtube.com/watch?v=GjVdXKrRuRo', 'vento1.jpg', 'vento2.jpg', 'vento3.jpg', 'vento4.jpg', 'vento5.jpg', 'vento6.jpg', 'vento7.jpg', 'vento8.jpg', 'vento9.jpg', 'vento10.jpg'),
(28, 'Hyundai Creta', '12.00', 'SUV', 'Hyundai ', 'Creta', 12, 18, 89, 219, 165, 'White , Red , Black', 5, 'Both', 'Both', 5, 55, ' After completing a successful year in July 2016, Hyundai launched the Anniversary Edition of the Hyundai Creta, which is available only on the SX+ trim. The significant changes can be seen at the exterior. Available in only one colour scheme, i.e. white, it gets a glossy black paint finish on the roof along with the pillars. Marking the event, this variant sports a ‘1 Anniversary Edition’ decal on the C-pillars while dual colour decal strips in matte grey and red are also a part of the package. Subtle changes can be seen at the rear as well with a body-coloured bar at the top of the number plate on the tailgate instead of a chrome set-up. Complementing its sporty exterior, Hyundai has opted for a red and black layout for the cabin. Seats along with AC vents get a red-treatment while the steering wheel gets draped in leather. The compact SUV was also launched in an automatic avatar in April. But it''s available only in petrol and SX+ trim, which retails for Rs 12.86 lakh (ex-showroom, Delhi). Along with the introduction of the new transmission, dual airbags are now standard across the range. The 1.6-litre petrol motor develops 123PS of power and 151Nm of torque. The Creta faces stiff competition from the likes of the Renault Duster and the Nissan Terrano.', 4, 10, 4270, 1780, 1630, 2590, 1180, 190, 400, 'https://youtu.be/8Fn-i8Wd5yM', 'creta1.jpg', 'creta2.jpg', 'creta3.jpg', 'creta4.jpg', 'creta5.jpg', 'creta6.jpg', 'creta7.jpg', 'creta8.jpg', 'creta9.jpg', 'creta10.jpg'),
(3, 'Volkswagen Tiguan', '25.00', 'SUV', 'Volkswagen', 'Tiguan', 11, 14, 184, 340, 220, 'Silver, Black, Grey', 4, 'Both', 'Both', 5, 75, 'The German car manufacturer, Volkswagen has unveiled Tiguan at the 2016 Indian Auto Expo. Based on Volkswagen’s MQB platform, the car will rival Ford Endeavour, Toyota Fortuner and Chevrolet Trailblazer. The MQB platform makes the car 100kg lighter than the PQ35 platform. Powering the car is a 2.0-litre diesel mill, that churns out a maximum power of 148bhp. The powerplant comes mated with 6-speed dual-clutch transmission and is also offered with AWD option for off-roading. At the Indian shores, the closest neck and neck will be with Ford Endeavour’s 2.2-litre powertrain that can generate a maximum power of 158bhp. The Tiguan gets some upgraded features like online assistance, automatic accident notification, traffic updates, parking space info and vehicle status report. On the safety aspects, the car gets airbags with ABS and EBD. Also, the music system accompanies Apple CarPlay and Android Auto for music enthusiasts.', 4, 5, 4485, 1839, 1632, 2681, 1890, 200, 620, 'https://www.youtube.com/watch?v=qac2clUtSlg', 'tig1.jpg', 'tig2.jpg', 'tig3.jpg', 'tig4.jpg', 'tig5.jpg', 'tig6.jpg', NULL, NULL, NULL, NULL),
(4, 'Skoda Superb', '23.00', 'Sedan', 'Skoda', 'Superb', 15, 17, 132, 320, 250, 'White, Black, Brown, Grey', 4, 'Both', 'Both', 5, 75, 'Skoda India has launched the next generation Superb sedan at Rs. 22.68 lac (ex-showroom Mumbai). The new Superb is already running in the European markets and now its time for the Indian car enthusiasts to put their hands over the new luxury loaded car. The new version incorporates several aesthetic changes with refreshed outer profile and an array of premium features inside the cabin. The new Superb has already got 5-star rating in Euro NCAP, keeping intact the brand''s safety values and commitments intact. In terms of powertrains, it gets 1.8 litre petrol and 2.0 litre diesel engines, mated to 6-speed manual or DSG automatic, depending upon the variant.', 4, 7, 4861, 1864, 1483, 2841, 1565, 149, 615, 'https://www.youtube.com/watch?v=jd8Wrwa0gA0', 'tig1.jpg', 'tig2.jpg', 'tig3.jpg', 'tig4.jpg', 'tig5.jpg', 'tig6.jpg', 'tig7.jpg', 'tig8.jpg', 'tig9.jpg', 'tig10.jpg'),
(29, 'Toyota Fortuner', '26.75', 'SUV', 'Toyota ', 'Fortuner', 8, 12, 169, 343, 176, 'White , Brown , Black ', 5, 'Both', 'Both', 8, 80, ' Toyota has brought the second generation of the Fortuner to the Bangkok International Motor Show 2016. The TRD version has a 2.8-litre diesel engine, which was introduced with the new Fortuner last year. The new diesel motor churns out 177bhp of power and 450 Nm of torque. The engine is mated to a 6-Speed automatic with paddle shifters. Performance upgrades include a Sigma 4WD system, TRD Sportivo suspension units, and larger discs brakes. The car is 90mm longer than its predecessor and is much more spacious. The new Fortuner will be launched in India next year (2017) with a competitive price tag.', 4, 10, 4705, 1840, 1850, 2750, 1880, 220, 296, 'https://youtu.be/-pMLsASJ1Vg', 'fortuner1.jpg', 'fortuner2.jpg', 'fortuner3.jpg', 'fortuner4.jpg', 'fortuner5.jpg', 'fortuner6.jpg', 'fortuner7.jpg', 'fortuner8.jpg', 'fortuner9.jpg', 'fortuner10.jpg'),
(5, 'BMW X3', '60.00', 'SUV', 'BMW', 'X3', 15, 19, 190, 400, 210, 'Brown, Grey, Silver, Black, Red, Blue', 4, 'Both', 'Both', 5, 67, 'BMW India has added a new variant in their X3 SUV lineup featuring M Sport package - xDrive30d M Sport. The variant is priced at Rs 59,90,000 (Ex-Showroom New, Delhi). And like the other X3 trims, it is also locally assembled at BMW’s Chennai facility and is now available at BMW dealerships across India. It adds M Aerodynamic package - beefed-up front and rear bumpers, Dark Shadow metallic color diffusers along with body colored wheel arch trim and door trim. The vehicles come in six exterior color shades including an exclusive shade - Carbon Black metallic. Moreover, it rides on M light alloy wheels and features ‘M’ logo on the sides. On the inside, apart from the usual X3 dashboard, it offers M leather steering wheel and BMW Individual - anthracite headliner. Mechanically, it is powered by the same 3.0-liter in-line 6-cylinder diesel.', 4, 5, 4657, 2089, 1678, 2810, 1650, 211, 550, 'https://www.youtube.com/watch?v=0_2R6zSrF3I', 'x31.jpg', 'x32.jpg', 'x33.jpg', 'x34.jpg', 'x35.jpg', 'x36.jpg', 'x37.jpg', 'x38.jpg', 'x39.jpg', 'x310.jpg'),
(30, 'Chevrolet Cruze', '13.95', 'Sedan', 'Chevrolet ', 'Cruze', 12, 16, 164, 360, 220, 'White , Red , Black , Grey , Brown', 5, 'Both', 'Both', 5, 60, 'Chevrolet Cruze is one of the most value for money car that one can buy in India, today. The American automaker recently slashed the prices of this car by Rs. 85,000. The new Chevrolet Cruze facelift is now priced at Rs. 14 lacs (ex-showroom, New Delhi) and for this price tag, which can easily be one of a compact SUV, you will get a 2.0-litre diesel powerplant, which is capable of churning out 163.7bhp of power output. This means, in terms of overall power alone, Chevrolet Cruze can lay waste to the likes of Audi A3 and previous generation Audi A4, which even in the pre-owned car market will cost you well over the Rs. 14 lacs mark.', 4, 9, 4597, 1788, 1477, 2685, 1525, 165, 450, 'https://youtu.be/kMzp1wgws-s', 'cruze1.jpg', 'cruze2.jpg', 'cruze3.jpg', 'cruze4.jpg', 'cruze5.jpg', 'cruze6.jpg', 'cruze7.jpg', 'cruze8.jpg', 'cruze9.jpg', 'cruze10.jpg'),
(31, 'Tata Nano ', '2.50', 'Hatchback', 'Tata', 'Nano', 20, 24, 38, 51, 105, 'Red , Yellow , White , Blue ', 5, 'Petrol', 'Manual', 4, 24, 'The Tata Nano is a smart city car and is among the most affordable ones available. Due to its short overhangs and high ground clearance, manoeuvring the Nano in the city is a breeze. Powered by a 624cc engine, it belts out a decent 38PS of max power and 51Nm of peak torque. In more recent news, the Tata Nano electric has been spied testing in Maharashtra. However, don''t expect it to launch anytime soon.', 2, 14, 3164, 1750, 1652, 2230, 695, 180, 110, 'https://youtu.be/0Ro9UxwgQKs', 'nano1.jpg', 'nano2.jpg', 'nano3.jpg', 'nano4.jpg', 'nano5.jpg', 'nano6.jpg', 'nano7.jpg', 'nano8.jpg', 'nano9.jpg', 'nano10.jpg'),
(6, 'Maruti Suzuki Swift', '6.70', 'Hatchback', 'Maruti Suzuki', 'Swift', 21, 25, 74, 190, 150, 'Red, Black, Grey, Silver', 4, 'Both', 'Manual', 4, 45, 'Maruti Suzuki had introduced the mid-life update of the second-generation Swift in the country in October 2014. The facelifted version came with subtle aesthetic improvements along with a few additional features – such as push-button engine start-stop, reverse parking sensors, electronically foldable outside rear-view mirrors, Bluetooth phone integration, and others – over the previous version. There were subtle changes to the front bumper as well; and it came with new upholstery. Mechanically, the Swift’s fuel efficiency was improved by 10 per cent with the mid-life update and, to deliver it, its existing (1.2-litre petrol and 1.3-litre diesel) engines were tweaked slightly. After the introduction of the facelift, over the course of two years, Maruti has come up with a few special editions of the Swift, and the latest one is the Swift ‘Deca’. It was showcased at the 2016 Auto Expo.', 4, 10, 3850, 1695, 1530, 2430, 1505, 170, 204, 'https://www.youtube.com/watch?v=W1IqyP5nUy8', 'swift1.jpg', 'swift2.jpg', 'swift3.jpg', 'swift4.jpg', 'swift5.jpg', 'swift6.jpg', 'swift7.jpg', 'swift8.jpg', 'swift9.jpg', 'swift10.jpg'),
(32, 'Mercedes-Benz C-Class', '45.00', 'Sedan', 'Mercedes Benz', 'C Class', 16, 19, 170, 400, 233, 'Metallic grey , White , Black ', 4, 'Both', 'Both', 5, 66, 'The new C-Class has created a new benchmark in its segment with its modern, aesthetic design, high-class interiors and cutting-edge technology. Its features include exemplary safety and high efficiency, while boasting of sporty and agile handling. These class leading features have also made the car a favorite with the critics and jury members of the prestigious automotive awards in India this year. The new C-Class’ 4-cylinder diesel engine is the most fuel efficient in the segment with a fuel efficiency of 19.27 km per litre. Together with a large fuel tank capacity of 66 litres it gives the customers freedom to explore places around them without worrying about frequent trips to the fuel station. The engine also boasts of ECO start/stop function which helps in saving fuel and reducing emissions. The engine produces 125 kW at 3000-4200 rpm with a maximum torque of 400 Nm between 1400-2800 rpm, which is highest in the segment. It accelerates from 0 to 100 kmph in 7.4 seconds with a top speed of 233 kmph.', 4, 6, 4868, 2020, 1442, 2840, 1655, 157, 480, 'https://youtu.be/CCEVC9_I3bY', 'benzc1.jpg', 'benzc2.jpg', 'benzc3.jpg', 'benzc4.jpg', 'benzc5.jpg', 'benzc6.jpg', 'benzc7.jpg', 'benzc8.jpg', 'benzc9.jpg', 'benzc10.jpg'),
(7, 'Maruti Suzuki Eeco', '4.70', 'MUV', 'Maruti Suzuki', 'Eeco', 12, 16, 73, 101, 145, 'Blue, Silver, Red, Black, Grey', 5, 'Both', 'Manual', 7, 40, 'Maruti Suzuki India in keeping with the current market trend has released a limited edition Eeco dubbed as Maruti Eeco Smiles at a starting price of Rs. 3.32 lakh (Ex-showroom, Mumbai) . This limited edition model does not feature mechanical changes but boasts of plenty cosmetic ones. The new Eeco Smiles comes with wheel covers, mud flaps and ''Smiles'' stickers on the side profiles and the rear. Inside the cabin it now sports a new double DIN music system with USB, new doormats and dual tone seat covers. All these extra features have added Rs. 9,490 to the price of the car. The car houses a 1.2-litre petrol engine that generates a maximum power output of 73bhp along with 101Nm of peak torque, while returning an impressive mileage of around 15kmpl. The vehicle is also available with the CNG kit option, which promises to return a mileage of 20km/kg.', 4, 10, 3675, 1475, 1800, 2350, 1510, 160, 540, 'https://www.youtube.com/watch?v=W2RojF3b5zM', 'eco1.jpg', 'eco2.jpg', 'eco3.jpg', 'eco4.jpg', 'eco5.jpg', 'eco6.jpg', 'eco7.jpg', 'eco8.jpg', 'eco9.jpg', 'eco10.jpg'),
(8, 'BMW i8', '201.00', 'Hybrid', 'BMW', 'i8', 37, 47, 231, 320, 250, 'Silver, Grey, Blue', 2, 'Petrol', 'Automatic', 4, 42, 'BMW is to launch a facelift for its i8 model by end 2017. The hybrid sports car will get upgrades in powertrain, chassis and overall design. While the current 1.5-litre turbo petrol mill coupled to an electric motor generates 362hp, the updated combination is likely to churn out 425 horses. This is approximately 18 per cent increase in power. The German carmaker is likely to introduce the induction charging option also in the facelift. Apart from this, it will focus on weight reduction by using carbon-fibre tyres instead of aluminium ones.', 3, 2, 4689, 1942, 1291, 2800, 1560, 117, 154, 'https://www.youtube.com/watch?v=SMEn-kQP4nM', 'i81.jpg', 'i82.jpg', 'i83.jpg', 'i84.jpg', 'i85.jpg', 'i86.jpg', 'i87.jpg', 'i88.jpg', 'i89.jpg', 'i810.jpg'),
(9, 'AUDI A3 Cabriolet', '48.60', 'Çonvertible', 'AUDI', 'A3 Cabriolet', 13, 17, 177, 250, 240, 'Grey, Silver, Red, Blue, Brown', 2, 'Both', 'Both', 4, 50, 'Audi India has finally introduced the auto expo-showcased A3 Cabriolet at a price of INR 44.75 Lacs. The Cabriolet is a sporty iteration of the brand''s cheapest and most compact offering, the A3 sedan. Unlike the A3, which is assembled locally, the Cabriolet comes as a direct import in form of a Complete Built Unit (CBU) in the country. Based on the same Volkswagen group’s versatile- MQB platform, the car comes with a single engine option. The 1.8-liter TFSI turbo petrol mill, which already powers the A3 sedan, also powers this latest offering from the German brand. The mill is good for 177 bhp and 280 Nm.', 4, 4, 4421, 1960, 1409, 2595, 1430, 165, 320, 'https://www.youtube.com/watch?v=V3JzQusOstk', 'a31.jpg', 'a32.jpg', 'a33.jpg', 'a34.jpg', 'a35.jpg', 'a36.jpg', 'a37.jpg', 'a38.jpg', 'a39.jpg', 'a310.jpg'),
(33, 'Toyota Prius ', '40.00', 'Sedan', 'Toyota', 'Prius', 23, 25, 98, 142, 112, 'Red , White , Grey , Black', 4, 'Petrol', 'Both', 5, 45, 'When the Prius first went on sale in Japan back in 1997, it combined the power of a conventional petrol engine and an electric motor, making it the first mass-produced hybrid vehicle. Toyota then introduced it globally in 2000 and since then, the Prius is being sold in nearly 80 countries including India.  Exterior  Being a hybrid vehicle, the Prius looks quite distinctive when compared to conventional petrol or diesel powered cars currently sold in the Indian market. The large front air dam and the boomerang-shaped headlights lend an aggressive presence on the road. The 15-inch wheels on the side may look puny but the low resistance tyres help maximise the fuel economy. At the back, the vertically stacked LED tail lamps not only look good but also use less power compared to conventional bulbs.  Interior  The interior is as distinctive as the exterior with its swooping dashboard design and the unique looking electronic gear stick. The Prius also gets a head-up display which projects various driving information, centre meter display, a touch screen display and climate control. It also gets USB compatible multimedia system, smart entry with push-button start, back monitor and lots more.', 4, 10, 4460, 1745, 1510, 2700, 1390, 135, 612, 'https://youtu.be/4XEDhtz989Y', 'prius1.jpg', 'prius2.jpg', 'prius3.jpg', 'prius4.jpg', 'prius5.jpg', 'prius6.jpg', 'prius7.jpg', 'prius8.jpg', 'prius9.jpg', 'prius10.jpg'),
(34, 'BMW M Series M4 Coupe', '130.00', 'Coupe', 'BMW', 'M4 Coupe', 10, 12, 431, 550, 230, 'Black , Austin yellow , Orange , White , Mineral grey , Aqua Blue', 2, 'Both', 'Automatic', 2, 63, 'BMW has always captured the finest elements to make a car, and successfully unleashed them into entities of grandeur and luxury. This all new model shows the world just why this prominent company dazzles in what they do. The BMW M Series M4 Coupe stands as one of the rarest and most exquisite machines to cruise our streets. The two door vehicle is a blend of both performance and style: It is destined to rule our streets with speed and ferocity, but without compromising on luxury and comfort. This high end sports machine is powered by a M TwinPower turbo engine, which sends it sailing to exhilarating top speeds rarely seen on Indian streets. This high rev engine is built as a six cylinder petrol format. Translating the massive engine capacity to speed is a seven gear dual clutch transmission system, specially designed for the needs of expensive machine. The inner prowess is balanced by the beauty that paints it from the outside: Its low profile is designed for aerodynamics and stealth on the streets. Its fluidic, streamlined shape gives it an imposing look rarely found on regular roads. Its trimmed front grille, stylistically shaped headlights and elegant bumper are all sure to bring it to the fore of all its viewers'' eyes.', 6, 4, 4671, 2014, 1383, 2812, 1612, 121, 445, 'https://youtu.be/8X_DnQcayF0', 'm41.jpg', 'm42.jpg', 'm43.jpg', 'm44.jpg', 'm45.jpg', 'm46.jpg', 'm47.jpg', 'm48.jpg', 'm49.jpg', 'm410.jpg'),
(10, 'Fiat Abarth Punto', '10.50', 'Hatchback', 'Fiat', 'Abarth Punto', 12, 16, 145, 212, 190, 'Red', 5, 'Both', 'Manual', 5, 45, 'Fiat India has launched the Abarth Punto Evo and Avventura powered by Abarth, which happens to be its steroid infused hatchback and crossover. Powering these ‘Scorpion Stung’ cars is a 1.4-litre turbocharged T-Jet petrol unit that churns out 145 BHP in Abarth Punto and 140bhp in Avventura. Unlike its elder sibling, the 595 Competizione, the cars get a 5-speed manual transmission and hit the 100 kmph mark from a standstill in under 8.8 seconds (Punto) and 9.9 seconds (Avventura).', 4, 4, 3989, 1687, 1505, 2510, 1320, 155, 280, 'https://www.youtube.com/watch?v=RXPUQorXQiU', 'pu1.jpg', 'pu2.jpg', 'pu3.jpg', 'pu4.jpg', 'pu5.jpg', 'pu6.jpg', 'pu7.jpg', 'pu8.jpg', 'pu9.jpg', 'pu10.jpg'),
(11, 'Renault Duster', '12.50', 'SUV', 'Renault', 'Duster', 16, 20, 84, 200, 156, 'Red, Orange, Black, Grey, Green', 5, 'Both', 'Both', 5, 50, 'The Renault Duster has started to face the heat with the Vitara Brezza and the Hyundai Creta crunching good numbers in the SUV space. Earlier in March, Renault launched the facelifted Duster at a price tag of Rs. 8.47 lakh. The top of the line, AWD (4x4) variant of the SUV was priced at Rs. 13.57 lakh whereas the 6 speed Easy-R AMT began from Rs. 11.67 lac (all prices ex-showroom Delhi). Duster facelift has the new ‘CMO10’ & ‘T4 E&E’ architecture which enables enhanced safety, better ride and handling for the SUV. It is available in five trim levels – Standard, RXE, RXL, RXS, and RXZ, with both diesel and petrol engine options.', 4, 6, 4315, 1822, 1695, 2673, 1570, 205, 475, 'https://www.youtube.com/watch?v=Oc18LAMUVSc', 'du1.jpg', 'du2.jpg', 'du3.jpg', 'du4.jpg', 'du5.jpg', 'du6.jpg', 'du7.jpg', 'du8.jpg', 'du9.jpg', 'du10.jpg'),
(35, 'Ford EcoSport ', '8.50', 'SUV', 'Ford ', 'EcoSport ', 20, 23, 99, 205, 182, 'Orange , White , Metallic Grey , Silver , Chocolate Brown', 5, 'Both', 'Both', 5, 52, 'The EcoSport introduced Ford’s new face in the country. The wide gaping grille with swept back headlamps stacked high up gives the EcoSport its SUV appeal. The flared wheel arches on the side profile and the raked windscreen make it look sporty. The kinetic design continues to the side-hinged tailgate. It looks busy in a way and the 200mm ground clearance gives it the SUV stance.  The interior is in black and grey and looks premium especially with the blue backlit buttons on the centre console. The dashboard is has its curves and blends with the overall design of the car. The twin pod instrument cluster reads out all the vital information including fuel economy, distance to empty, average speed et al along with the car and engine speeds. It gets automatic climate control for the top-spec variant along with height adjustable driving seats. The top-end trim gets six airbags for safety along with ABS while the mid variant gets dual front airbags and ABS.', 4, 12, 3999, 1766, 1708, 2520, 1800, 200, 346, 'https://youtu.be/TKPrp7GB3ts', 'ecosport1.jpg', 'ecosport2.jpg', 'ecosport3.jpg', 'ecosport4.jpg', 'ecosport5.jpg', 'ecosport6.jpg', 'ecosport7.jpg', 'ecosport8.jpg', 'ecosport9.jpg', 'ecosport10.jpg'),
(100, 'Honda City', '10.44', 'Sedan', 'Honda', 'City', 23, 26, 99, 200, 175, 'White, Silver,Glossy Black', 5, 'Both', 'Both', 5, 40, 'The Honda City is available with a 119PS, 1.5-litre petrol engine, mated to a five-speed manual or a CVT automatic gearbox and a 100PS, 1.5-litre diesel engine mated to a six-speed manual transmission. It comes in six different colours across seven diesel and nine petrol variants, starting from Rs 8.10 lakh and going up to Rs 12.48 lakh (ex-showroom, Delhi). The sedan recently crossed the two-lakh sales milestone in just under three years in India and has been the highest-selling car for Honda since October 2015. In terms of safety, the sedan comes with dual SRS airbags, ABS with EBD and Advanced Compatibility Engineering (ACE) body shell.', 4, 10, 4440, 1695, 1495, 2600, 1125, 165, 510, 'https://www.youtube.com/watch?v=RlCuE7payxI', 'city1.jpg', 'city2.jpg', 'city3.jpg', 'city4.jpg', 'city5.jpg', 'city6.jpg', 'city7.jpg', 'city8.jpg', 'city9.jpg', 'city10.jpg'),
(101, 'Honda Jazz', '7.55', 'Hatchback', 'Honda', 'Jazz', 24, 28, 99, 200, 172, 'Fire Red,Black,White', 5, 'Both', 'Both', 5, 40, 'Honda first introduced the Jazz in India in 2009 when the car was in its second generation globally. Back then, the brand was running a petrol-only brigade and as a result, the Jazz featured a 1.2-litre i-VTEC petrol engine. Now in its third generation, the all-new Honda Jazz is available with both petrol and diesel power to take on the growing premium hatchback segment.The new Jazz is as tall and wide as the old car, however, it is longer by 55mm and features a wheelbase that is lengthened by 30mm. The improved length helps increase the cabin space and overall comfort levels. As for the design, the overall layout of the cabin is somewhat similar to the City.The new Jazz features a sportier, aerodynamically enhanced form of the old car. What this means is that it carries the same mini MPV-like profile of the old model albeit with a modern touch. The new design language, in fact, brings the Jazz in line with Honda’s new range of models that have been flooding several global markets.', 4, 13, 3955, 1694, 1544, 2530, 1130, 165, 354, 'https://www.youtube.com/watch?v=XTRAwVmxcJU', 'jazz1.jpg', 'jazz2.jpg', 'jazz3.jpg', 'jazz4.jpg', 'jazz5.jpg', 'jazz6.jpg', 'jazz7.jpg', 'jazz8.jpg', 'jazz9.jpg', 'jazz10.jpg'),
(36, 'Ford Endeavour ', '27.75', 'SUV', 'Ford', 'Endeavour', 10, 12, 158, 385, 180, 'Red , Black , White , Brown', 5, 'Both', 'Both', 7, 80, ' Ford India has silently updated the prices of its Endeavour SUV which now calls for a massive price cut of up to Rs 2.82 lakh. However, the price drop is only seen in the Trend trim while the Titanium’s price remains unchanged. Launched in August this year, the car competes with the likes of the Chevrolet Trailblazer and the Toyota Fortuner. The Endeavour features almost all the attributes needed by an off-roader while travelling through difficult terrains. This American car comes with two engine options viz. 3.2L and 2.2L. While the more powerful engine can produce a maximum power of 200PS with 470Nm torque, 2.2L engine will generate 160PS of power with a peak torque of 385Nm.', 4, 10, 4892, 1860, 1837, 2850, 1879, 225, 400, 'https://youtu.be/3Qf6CfMhSwo', 'endeavour1.jpg', 'endeavour2.jpg', 'endeavour3.jpg', 'endeavour4.jpg', 'endeavour5.jpg', 'endeavour6.jpg', 'endeavour7.jpg', 'endeavour8.jpg', 'endeavour9.jpg', 'endeavour10.jpg'),
(102, 'Honda Amaze', '7.11', 'Sedan', 'Honda', 'Amaze', 21, 27, 99, 200, 170, 'Shiny Blue,White,Black', 5, 'Both', 'Both', 5, 40, 'Honda has updated their sub-four-metre compact sedan three years after its launch in 2013. This midlife upgrade brings the Honda Amaze at par with its competition. The Amaze is basically a sedan version of the Brio, but looks proportionate, unlike few of its competitors. The important bit is that the Amaze refuses to look boring, whether you like the way it looks or not.The Honda Amaze petrol is powered by refined 1.2-litre i-VTEC producing 88bhp of power and 109Nm of torque, the same unit that powers the Brio, with the ARAI fuel economy of 17.8kmpl. The sub-four metre sedan also gets a CVT automatic petrol variant with an ARAI fuel efficiency of 18.1kmpl. ', 4, 17, 3990, 1680, 1505, 2405, 1050, 165, 400, 'https://www.youtube.com/watch?v=yEEFLYO5tWE', 'amaze1.jpg', 'amaze2.jpg', 'amaze3.jpg', 'amaze4.jpg', 'amaze5.jpg', 'amaze6.jpg', 'amaze7.jpg', 'amaze8.jpg', 'amaze9.jpg', 'amaze10.jpg'),
(37, 'Honda CR-V', '25.00', 'SUV', 'Honda', 'CR-V', 12, 15, 154, 190, 190, 'Red , Black , White , Chocolate Brown , Metallic Grey', 5, 'Both', 'Both', 5, 58, 'CR-V began to be locally assembled (at the company’s Noida manufacturing facility). Despite being in the market for so long, the car has, as such, no direct competitors till date since it is available solely as a petrol offering, as opposed to almost all other cars in its price band – Rs 22-26 lakh (ex-showroom New Delhi) – being diesel-powered ones. The crossover/SUV is available with two four-cylinder, naturally aspirated petrol engine options – a 2.0-litre and a 2.4-litre option. The former is available either with a six-speed manual or CVT (continuously variable transmission), while the latter is only available with a CVT automatic transmission. ', 4, 9, 4545, 1820, 1685, 2620, 1480, 200, 589, 'https://youtu.be/1nqHenVcA80', 'crv1.jpg', 'crv2.jpg', 'crv3.jpg', 'crv4.jpg', 'crv5.jpg', 'crv6.jpg', 'crv7.jpg', 'crv8.jpg', 'crv9.jpg', 'crv10.jpg'),
(103, 'Maruti Baleno', '6.62', 'Hatchback', 'Maruti', 'Baleno', 23, 28, 74, 190, 160, 'Red,Silver,Blue', 5, 'Both', 'Both', 5, 37, 'The Baleno is the new B+ segment hatchback from Maruti Suzuki. The compact car is positioned above the Swift in the Maruti Suzuki range, making it their most premium hatchback in India.The Baleno uses Suzuki’s new liquid flow design philosophy to emphaise its exterior. The front of the car gets V-shaped grille, whose lines are extended all the way to the rear, first through the sweptback headlamps and then through the shoulder line.The cabin looks refreshing with the new dashboard layout. The all-black interior is sporty and there are silver inserts for the dashboard and door trims. There is plenty of space in the cabin for five passengers, also the boot is large at 339 litres.', 4, 15, 3995, 1745, 1500, 2520, 960, 170, 339, 'https://www.youtube.com/watch?v=NxcFgY_S2Z8', 'baleno1.jpg', 'baleno2.jpg', 'baleno3.jpg', 'baleno4.jpg', 'baleno5.jpg', 'baleno6.jpg', 'baleno7.jpg', 'baleno8.jpg', 'baleno9.jpg', 'baleno10.jpg'),
(104, 'Maruti Swift', '5.76', 'Hatchback', 'Maruti', 'Swift', 21, 26, 74, 190, 155, 'Red,Black,Silver', 5, 'Both', 'Both', 5, 42, 'Exterior  When it comes to looks....the all new swift beats all its competitors....it''s high end Aerodynamic design and the front grill is attractive enough that you would fall in love with it.....  Interior (Features, Space & Comfort) The all new Sporty steering wheel gives the perfect grip...Also the additional storage space such as Retractable cup Holders and storage pockets at the door gives sufficient space to carry our regular belongings...  Engine Performance, Fuel Economy and Gearbox  The engine is really smooth.It produces very less noise as compared to other cars of the segment and gives the meaning to its name....Swift!!When it comes to fuel economy Maruti Suzuki has always offered best in class fuel economy which is secret of its survival even after getting competitions from the Foreign rivals like Nissan,Chevrolet,Hyundai,Honda which are all concentrating on the same segment Swift belongs.', 4, 14, 3850, 1695, 1530, 2430, 1100, 170, 204, 'https://www.youtube.com/watch?v=W1IqyP5nUy8', 'swift1.jpg', 'swift2.jpg', 'swift3.jpg', 'swift4.jpg', 'swift5.jpg', 'swift6.jpg', 'swift7.jpg', 'swift8.jpg', 'swift9.jpg', 'swift10.jpg'),
(38, 'Toyota Corolla Altis', '16.45', 'Sedan', 'Toyota ', 'Corolla Altis', 20, 22, 88, 205, 170, 'Blue , White , Silver , Grey , Metallic Blue', 5, 'Both', 'Both', 5, 50, 'The new Corolla petrol starts at a very competitive Rs 11.99 lakh while the base diesel costs Rs 13.07 lakh, which is cheaper than the competition. But as you start going up the spec-chain, they get quite expensive. Our top-spec test cars cost Rs 16.89 lakh for the petrol automatic and Rs 16.68 lakh for the diesel manual. So if you choose the diesel, there’s a whopping difference of Rs 3.61 lakh for a car that’s mechanically identical across variants! While the lower entry prices may have been devised to increase footfall in showrooms, the lower variants are quite barebone and you’ll have to shell out significantly more for a trim with at least a half-decent level of kit.', 4, 8, 4620, 1775, 1475, 2700, 1260, 175, 470, 'https://youtu.be/XpEmXOshkp4', 'corolla1.jpg', 'corolla2.jpg', 'corolla3.jpg', 'corolla4.jpg', 'corolla5.jpg', 'corolla6.jpg', 'corolla7.jpg', 'corolla8.jpg', 'corolla9.jpg', 'corolla10.jpg'),
(105, 'Maruti Ciaz', '7.73', 'Sedan', 'Maruti', 'Ciaz', 20, 25, 88, 200, 190, 'Red,Silver,Grey,Brown', 5, 'Both', 'Both', 5, 43, 'The Ciaz is Maruti Suzuki’s first shot at a premium sedan and keeping that in mind, it looks very impressive. If its rivals boast of sleek and edgy design, the Ciaz gets a more pronounced and muscular styling. The premium bits across the exterior profile are impressive.It is a Maruti Suzuki car and thus comes with functional interiors as a given. In addition to making it feel practical, they have added modernity in the design which is a distinguishing factor.It feels plush and rich and offers smart storage options too like the central armrest area which has a storage area for mundane articles and a provision to hold a pen and cards. The petrol engine is the next generation K-tech powered unit which promises better performance whereas the DDiS engine has been tweaked to deliver an amazing mileage of 26.21 kmpl along with lower NVH levels.', 4, 12, 4490, 1730, 1485, 2650, 1595, 170, 510, 'https://www.youtube.com/watch?v=HRlzagsAtFM', 'ciaz1.jpg', 'ciaz2.jpg', 'ciaz3.jpg', 'ciaz4.jpg', 'ciaz5.jpg', 'ciaz6.jpg', 'ciaz7.jpg', 'ciaz8.jpg', 'ciaz9.jpg', 'ciaz10.jpg'),
(39, 'Mini Cooper Convertible', '33.90', 'Çonvertible', 'BMW', 'Mini Cooper Convertible', 15, 18, 192, 280, 228, 'Metallic Grey , Forest Green , Matt Black , Red', 2, 'Both', 'Automatic', 4, 44, ' BMW India has finally launched their first Mini product of the year, the Mini Cooper Convertible at Rs 34.90 lakh (ex-showroom). The updated version embraces quite a number of changes with the most important being the revised electrically operated roof-top. The soft-top is now smoother to operate at up to speed of 30kmph and the retraction time is shortened to 18 seconds, as compared to the previous version. Moreover, there is inclusion of roll-over protection system that is deployed as soon as it senses a possible roll-over. In terms of specs, 2016 Mini Cooper Convertible will get 1.5-litre diesel and 1.5-litre petrol units that are capable of generating respective power outputs of 116bhp and 134bhp, mated to 6-speed manual or auto gearbox. ', 4, 6, 3723, 1683, 1414, 1295, 1370, 180, 125, 'https://youtu.be/BiuYoW50AXY', 'mini1.jpg', 'mini2.jpg', 'mini3.jpg', 'mini4.jpg', 'mini5.jpg', 'mini6.jpg', 'mini7.jpg', 'mini8.jpg', 'mini9.jpg', 'mini10.jpg'),
(40, 'Mitsubishi Pajero Sport ', '28.00', 'SUV', 'Mitsubishi ', 'Pajero Sport ', 12, 15, 178, 350, 190, 'Yellow , Red , White , Black , Silver', 5, 'Both', 'Both', 7, 70, ' Mitsubishi India has reportedly launched a limited edition of its Pajero Sport SUV in the country. The limited run edition comes with aesthetic updates along with mechanical upgrades, exclusive to the automatic variant. There are no changes to the interiors of the SUV. Moreover, the automaker has also added two new color shades for this limited edition model. Speaking of the mechanical upgrades, the automatic variant featuring 5-Speed automatic with paddle shifters, now offers 4WD. Earlier, the auto trim was only available with a 4x2 layout. Apart from this, the vehicle remained unaltered mechanically.', 4, 10, 4695, 1815, 1840, 2800, 2600, 215, 500, 'https://youtu.be/fbFRDdf1PoI', 'pajero1.jpg', 'pajero2.jpg', 'pajero3.jpg', 'pajero4.jpg', 'pajero5.jpg', 'pajero6.jpg', 'pajero7.jpg', 'pajero8.jpg', 'pajero9.jpg', 'pajero10.jpg'),
(41, 'Hyundai Elantra', '16.42', 'Sedan', 'Hyundai ', 'Elantra', 18, 21, 126, 259, 191, 'White , Polar White , Blue , Black , Red', 5, 'Both', 'Both', 5, 420, 'Hyundai has launched the sixth-generation Elantra in India at an introductory price of Rs 12.99 lakh (ex-showroom Delhi). Presently, the Elantra competes with sedans such as the Toyota Corolla Altis, the Volkswagen Jetta, the Chevrolet Cruze, and the Skoda Octavia. The prices of the Elantra petrol start at around Rs 12.99 lakh, while the top-of-the-line diesel automatic costs Rs 19.99 lakh (all ex-showroom, Delhi). Mechanically, the Elantra comes with two engine options – a 2.0-litre VTVT petrol and a 1.6-litre CRDi diesel. The 1,999cc petrol puts out 152PS at 6,200rpm and 178Nm of max torque at 4,700rpm. The 1,582cc diesel produces 128PS at 4,000rpm and 260Nm of peak torque in between 1,900-2,750rpm. Transmission options include six-speed manual and automatic, with both the engines. Hyundai dealerships have started accepting bookings for the new Elantra at a token amount of around Rs 25,000. Among important changes, it gets a brand new 2.0-litre naturally aspirated Atkinson cycle petrol engine. Within eight days of arrival of the sedan in the country, Hyundai has registered 7,817 enquiries and 405 bookings and is going strong.', 4, 7, 4570, 1800, 1465, 2700, 1600, 165, 420, 'https://youtu.be/8c34omiSLyE', 'elantra1.jpg', 'elantra2.jpg', 'elantra3.jpg', 'elantra4.jpg', 'elantra5.jpg', 'elantra6.jpg', 'elantra7.jpg', 'elantra8.jpg', 'elantra9.jpg', 'elantra10.jpg'),
(42, 'Porsche Cayenne ', '125.00', 'SUV', 'Porsche  ', 'Cayenne', 14, 17, 300, 400, 230, 'Jet Black , White Turbo , Metallic White , Moonlight Blue , Meteor Blue , Silver Metallic', 5, 'Both', 'Both', 5, 85, ' Porsche India has introduced the updated Cayenne at a starting price of INR 1.04 crore (ex-showroom, Delhi). The luxury SUV comes in four variants namely the Diesel, S Diesel, S and the range-topping Turbo. Powering the S is a new 420bhp-3.6-litre bi-turbo V6 engine. While the diesel comes with 245bhp-3.0-litre V6 engine, and 385bhp-4.2-litre V8 engine gives force to the S Diesel. Last but not the least, the top of the line, Turbo, comes equipped with mighty 520bhp-4.8-litre bi-turbo V8 mill.', 6, 4, 4855, 1939, 1705, 2895, 2040, 215, 1780, 'https://youtu.be/-iRnc7gIVks', 'cayenne1.jpg', 'cayenne2.jpg', 'cayenne3.jpg', 'cayenne4.jpg', 'cayenne5.jpg', 'cayenne6.jpg', 'cayenne7.jpg', 'cayenne8.jpg', 'cayenne9.jpg', 'cayenne10.jpg'),
(106, 'Toyota Innova', '13.10', 'MUV', 'Toyota', 'Innova', 10, 13, 101, 200, 155, 'Silver,White,Gold', 5, 'Both', 'Both', 7, 55, 'Anything you expect from an MUV you will get in the all new Toyota Innova 2.5 GX 7 STR BS-IV Diesel variant. A classic feel, a compact appearance and no frills attitude – that’s Toyota’s upgraded MUV for you. The body colored bumper and rear view OVRMs give a feel of continuity to the body.The interiors have a lot of character in them thanks to the fabric upholstery in the seats and the fully air conditioned interiors. As for space, there’s enough of it for both the passengers and the luggage. Whether it’s a normal office day or a long road trip with family, the Toyota Innova 2.5 GX 7 STR BS-IV Diesel delivers either ways.This variant from Toyota gives a city mileage of 9kmpl and highway mileage of 12.99 kmpl. The BS-IV standardization has made it extremely fuel efficient. ', 4, 13, 4585, 1765, 1760, 2750, 1675, 176, 300, 'https://www.youtube.com/watch?v=TVhLVagZoK8', 'innova1.jpg', 'innova2.jpg', 'innova3.jpg', 'innova4.jpg', 'innova5.jpg', 'innova6.jpg', 'innova7.jpg', 'innova8.jpg', 'innova9.jpg', 'innova10.jpg'),
(43, 'BMW X6', '150.00', 'SUV', 'BMW ', 'X6', 16, 18, 313, 630, 240, 'Mineral White , Mineral Grey , Grey , Black , Glacier Silver , Flame Red', 4, 'Both', 'Both', 4, 85, 'After months of speculation, BMW India has finally reintroduced its lustrous SUV, X6 in the country. This four-wheeler represents a new breed of styling in the SUV segment owing to its coupe like silhouette and bold body structure. This model from the German auto giant has been introduced in only one variant with M sport package as standard. This second generation version has made its debut at the last year''s auto expo held in Moscow. The company claims that this SUV was produced and comprehensively re-engineered with the third generation X5 in a joint development program. The automaker also stated that this vehicle is about 40 Kgs lighter than its predecessor, as it is said to be built using high strength steel, aluminum and thermoplastics. It is already available in some international markets in a few trim levels, but in India, it comes only in xDrive40 trim. It is equipped with a an evolved 3.0-litre twin-turbo diesel engine under the hood. The manufacturer has updated the transmission with a newly developed 8-speed sport automatic transmission. It breaks the 100 Kmph barrier in just 5.8 seconds, which is remarkable for an SUV. ', 6, 4, 4909, 2170, 1702, 2933, 1800, 212, 550, 'https://youtu.be/guZUMCwrosg', 'x61.jpg', 'x62.jpg', 'x63.jpg', 'x64.jpg', 'x65.jpg', 'x66.jpg', 'x67.jpg', 'x68.jpg', 'x69.jpg', 'x610.jpg'),
(107, 'Mahindra Scorpio', '8.92', 'SUV', 'Mahindra', 'Scorpio', 10, 14, 115, 280, 154, 'Black,White,Red', 4, 'Both', 'Both', 5, 80, 'The mighty and muscular Scorpio is back in a new avatar - the first major generational leap in it''s 12 year run.  This is an all-new modular chassis that can be deployed for UVs of varying lengths and tracks (e.g. next-gen Quanto & Bolero). The company claims that the hydroformed chassis is twice as stiff as the older Scorpio''s and is safer as well. The front & rear axles are new, as are some suspension bits, while the gearbox is lifted from the updated Xylo. Mahindra has revamped the interiors too .The new Scorpio has an aggressive face that suits its robust nature. A tail-mounted spare could have totally transformed the rear end. The designers have added several flashy touches that might just be a hit with rural customers - LED tail-lamps, those controversial black protrusions (can be mistaken for grab handles), slots around the butterfly windows.This Beast is a all-time lover for car fanatic.', 4, 16, 5118, 1850, 1874, 3040, 1350, 180, 460, 'https://www.youtube.com/watch?v=epJqtMGk4Jk', 'scorpio1.jpg', 'scorpio2.jpg', 'scorpio3.jpg', 'scorpio4.jpg', 'scorpio5.jpg', 'scorpio6.jpg', 'scorpio7.jpg', 'scorpio8.jpg', 'scorpio9.jpg', 'scorpio10.jpg'),
(44, 'Audi Q7', '80.00', 'SUV', 'Audi', ' Q7', 15, 18, 245, 600, 234, 'Ink Blue , Graphite grey , Orca Black , Metallic Brown , Metallic Silver5', 5, 'Both', 'Both', 7, 75, 'Luxury car market in India is getting more and more customer oriented since the last couple of years. Among Germany''s Big 3, Audi is one automaker who has tasted immense success in the country owing to its contemporary models. Audi Q7 is its flagship SUV model, which is currently being offered as a CBU unit. Now, its facelifted version is launched in two trim levels, which are Premium Plus and Technology. It is about 300 kilograms lighter than the outgoing model, which will greatly enhance its overall performance and drive dynamics. This is powered by a 3.0-litre TDI oil burner that can generate 245.4bhp power in combination with 600Nm torque. Lowered weight and increased power output eventually offers a driving experience like never before. This motor is skillfully paired with an 8-speed tiptronic automatic transmission gear box. It is offered as a completely built-in unit, but its local manufacturing will start sometime in the next year at its Aurangabad facility. Its exterior styling has received a drastic improvement than before. The design concept of its signature grille remains the same, but the hexagonal surround got thicker in its size. The newly designed headlamps are available in three options namely, LEDs, xenon and Matrix LED lamps. Arrow shaped daytime running lights brings it more style, while both the bumpers are also tweaked. In the rear, it includes power operated tailgate as well as new LED tail lamps.  The interiors also has some significant improvements that are incomparably different from the outgoing model. Its cockpit has a premium design with admirable detailing all round. It also features an updated dashboard featuring a new infotainment system. It has neatly camouflaged cosmetics with modern layouts that set a new benchmark in the styling section. Audi''s “Virtual Cockpit” all digital instrument cluster and Drive Select will remain the other key highlight. Apart from the entertainment and communication sections, all its comfort features are retained from its predecessor. As for the safety, it comes with improved set of attributes that offer next level of protection. It takes on the likes of Mercedes Benz GL class, Volvo XC 90, Porsche Macan and BMW X5 in India.', 6, 4, 5052, 2212, 1740, 2994, 2330, 205, 295, 'https://youtu.be/JKP_4YqosS4', 'q71.jpg', 'q72.jpg', 'q73.jpg', 'q74.jpg', 'q75.jpg', 'q76.jpg', 'q77.jpg', 'q78.jpg', 'q79.jpg', 'q710.jpg'),
(108, 'Renault Kwid', '2.84', 'Hatchback', 'Renault', 'Kwid', 23, 26, 54, 72, 135, 'Red,SIlver,Brown', 5, 'Both', 'Both', 5, 28, 'The KWID’s design strategy symbolizes dynamic performance, robust strength and a taste for adventure. Its SUV-inspired stance off­ers a high driving position and greater visibility, making it ideal for zipping around in urban traffic or roaring down the open highway.The Renault KWID is powered by a brand new, state-of-the-art compact engine with advanced technology for accurate air to fuel ratio monitoring. A knock sensor automatically adjusts spark advance to fuel quality, to help deliver optimised performance.The Renault KWID comes equipped with a driver side airbag* and central locking system. The front disc brakes ensure you’re equipped for all weather conditions and road surfaces, while the high mount stop lamp and audible parking brake warning let you be with complete peace of mind all through the journey.', 3, 16, 3679, 1579, 1478, 2422, 389, 180, 300, 'https://www.youtube.com/watch?v=hdjUVSQ1zR4', 'kwid1.jpg', 'kwid2.jpg', 'kwid3.jpg', 'kwid4.jpg', 'kwid5.jpg', 'kwid6.jpg', 'kwid7.jpg', 'kwid8.jpg', 'kwid9.jpg', 'kwid10.jpg'),
(45, 'Toyota Land Cruiser', '100.00', 'SUV', 'Toyota ', 'Land Cruiser', 10, 12, 262, 650, 175, 'Black . Silver Metallic , Copper Brown , Dark Blue , Beige Mica', 5, 'Both', 'Both', 7, 93, 'Toyota Land Cruiser 200 has been launched with an update at a price tag of INR 1.29 Crore. The changes could be noticed on the outside as well as on the inside. But, s uch a jaw-dropping price is enough to make a style statement by the owner of this model vehicle. It is powered by a 4.5 litre 32 valve DOHC V8 diesel engine that produces a maximum power of 195 BHP at 3400 RPM and torque 650 Nm between 1600 to 2600 RPM. The new SUV boasts of new front grille, headlamps with HID low beams and freshly designed bumpers. It has a seating capacity of eight, with three-across seating in the second and third rows. This SUV, the costliest four wheeler of this company in India is essentially a four-wheel drive with automatic transmission and the beast is truly dominant on any kind of Indian road conditions.', 8, 8, 4950, 1980, 1910, 2850, 3350, 225, 258, 'https://youtu.be/jDTpNMHeYDg', 'landc1.jpg', 'landc2.jpg', 'landc3.jpg', 'landc4.jpg', 'landc5.jpg', 'landc6.jpg', 'landc7.jpg', 'landc8.jpg', 'landc9.jpg', 'landc10.jpg');
INSERT INTO `car` (`id`, `title`, `price`, `car_type`, `make`, `model`, `mileagec`, `mileageh`, `power`, `torque`, `top_speed`, `color`, `doors`, `fuel`, `transmisson`, `number_of_seats`, `fuelcapacity`, `ddesc`, `cylinders`, ` zerotosixty`, `Length`, `Width`, `Height`, `Wheelbase`, `Kerbweight`, `groundclearence`, `bootcapacity`, `video`, `photo1`, `photo2`, `photo3`, `photo4`, `photo5`, `photo6`, `photo7`, `photo8`, `photo9`, `photo10`) VALUES
(109, 'Lamborghini Aventador', '369.00', 'Coupe', 'Lamborghini', 'Aventador', 3, 5, 690, 690, 350, 'Fiery Orange', 2, 'Petrol', 'Both', 2, 90, ' Imagine what it feels like to sit in a trans-Atlantic airliner as it accelerates down the runway before take-off, how you instantly and uncontrollably get pushed back in your seat. Multiply that feeling by two. You’re still not quite there yet.The effortless-yet-brutal acceleration delivered by the V12 engine is something that every car fan needs to experience at least once in his or her life. And it needs to be experienced with your right foot mashing the skinny pedal, not as a passenger, in Gran Turismo .Power for the Aventador Roadster comes from a hand-built 6.5-liter twelve-cylinder engine tuned to deliver 690 horsepower at 8,250 rpm and 507 foot-pounds of torque at 5,500 rpm. The prodigious amount of grunt is generated by pure displacement; there are no turbos or superchargers hiding anywhere in the engine bay.  ', 12, 3, 4780, 2265, 1136, 2700, 1575, 125, 110, 'https://www.youtube.com/watch?v=Rmu4D7xocQU', 'lamborghini1.jpg', 'lamborghini2.jpg', 'lamborghini3.jpg', 'lamborghini4.jpg', 'lamborghini5.jpg', 'lamborghini6.jpg', 'lamborghini7.jpg', 'lamborghini8.jpg', 'lamborghini9.jpg', 'lamborghini10.jpg'),
(46, 'Audi Q3', '32.00', 'SUV', 'Audi', 'Q3', 16, 18, 138, 320, 202, 'Black , Blue , Red , Brown , Silver', 5, 'Both', 'Both', 5, 64, 'Audi India has launched the facelift version of Q3 compact luxury SUV at Rs. 28.99 lac (Ex-Showroom New Delhi). The 2015 model year vehicle is coming with added features, aesthetic uplift along with no mechanical changes. The SUV gets a new single-frame grille, Audi calls it ''3D-effect Singleframe'' grille. The new grille is finished in satin chrome and merges with the headlamps (LED headlamps are optional). It is pulled by the same 2.0-liter 35 TDI 4-cylinder oil burner. The engine musters out 174 bhp @ 4200 rpm and 380 Nm of max torque extracted in-between 1750-2500 rpm. The engine is mated to a 7-speed dual clutch automatic transmission. Moreover, with this facelift Audi has offered paddle shifters with the Q3.', 4, 6, 4388, 2019, 1608, 2603, 1520, 170, 460, 'https://youtu.be/dmgb40cF9sE', 'q31.jpg', 'q32.jpg', 'q33.jpg', 'q34.jpg', 'q35.jpg', 'q36.jpg', 'q37.jpg', 'q38.jpg', 'q39.jpg', 'q310.jpg'),
(110, 'Renault Fluence', '14.86', 'Sedan', 'Renault', 'Fluence', 17, 22, 108, 240, 185, 'White,Gold', 5, 'Both', 'Both', 5, 67, 'Renault Fluence is a treat for sedan lovers.The exterior is where the big changes are. The facelifted Fluence gets a new grille with a large Renault badge taking pride of place in the centre, the restyled headlamps look nice and there''s a new bumper with fog lamps. It also gets a new design for its 16-inch alloys. Overall, the nip and tuck has made the Fluence look much more modern and appealing.On the inside, there''s new seat leather, a new audio system, which sounds slightly better than the old unit, a soft touch dashboard with a hint of chrome around the air-con vents, dual-zone climate control, a digital instrument cluster with a blue tint around the speedometer, and an electronic parking brake. There’s also other kit like a smart key with start-stop button, cruise control, parking sensors, four airbags, anti-lock braking system (ABS), EBD, ESP, rain sensing wipers, automatic headlamps, rear sun blinds and rear air-con vents. At the rear seats, a lack of rear headroom is an issue in the low-roofed Fluence. But its long wheelbase translates to great legroom, even with the front seats pushed all the way back. The rear seats are comfortable, have great under-thigh support and the seating position is nice and upright.', 4, 15, 4618, 1813, 1488, 1703, 1150, 168, 530, 'https://www.youtube.com/watch?v=gMVTeeC_KBA', 'fluence1.jpg', 'fluence2.jpg', 'fluence3.jpg', 'fluence4.jpg', 'fluence5.jpg', 'fluence6.jpg', 'fluence7.jpg', 'fluence8.jpg', 'fluence9.jpg', 'fluence10.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
